[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  EXPO_PUBLIC_API_URL = "https://back-end-6b5z.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
